### ISSUE TITLE
Options screen search

### ISSUE THREAD

**Issue by ScorpionIbm** [brainfoolong/bomnibox#10]
The search in the options screen treats the default "SEARCH IN HISTORY" as text and when I tick the option to search in title and then uncheck it. The search uses the default text to perform a query. 
I know this is a minor issue but thought I should report it.

**Comment by brainfoolong** [comment]
Thanks, it's a real minor `issue`... I mark this as wontfix but i keep this in mind for the next, bigger update (if i do some update in the future)
