### ISSUE TITLE
Option to remove the "omniboxDefault" message in omnibar results

### ISSUE THREAD

**Issue by thatarchguy** [brainfoolong/bomnibox#11]
Having  "Use CTRL+SHIFT+0 to open quick history search without the omnibox" as the first option in the results all the time is obtrusive. An option to disable this message from showing would be ideal.

**Comment by brainfoolong** [comment]
As far as i know, this is impossible to change for extension developers. It's a default behaviour from chrome.

**Comment by thatarchguy** [comment]
That's unfortunate. Anyways, thanks for this chrome extension!
