### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by pbajorek** [brainfoolong/bomnibox#13]
I have a dumb question. What is the intended method to invoke this extension? Does it require two clicks? First on the toolbar icon, and then on Options? Thanks.

**Comment by brainfoolong** [comment]
Just enter `$` followed by a space in the omnibox.

**Comment by pbajorek** [comment]
Thank you. The description says the extension searches Chrome history. Does it also search bookmarks in addition to history?

**Comment by brainfoolong** [comment]
No, it's history only.

**Comment by pbajorek** [comment]
Please see the attached screenshots. Searching for "sticky". One of the images shows a history search reporting not found. The other is from bomnibox that shows an entry. It's as though bomnibox is showing from bookmarks. Am I using the extension correctly?
![chrome history search](https://user-images.githubusercontent.com/51709607/59428052-3edae380-8daa-11e9-926e-592ebf0a5d01.jpg)
![bomnibox image](https://user-images.githubusercontent.com/51709607/59428053-3edae380-8daa-11e9-9cd4-528522220d01.jpg)

**Comment by brainfoolong** [comment]
Pew. I am pretty sure that this stickynotes entry does not come from the bomnibox extension. It is impossible that this extension show bookmarks, there is no code that do this.
Maybe another extension is manipulating your omnibox?

**Comment by pbajorek** [comment]
From some reading, it appears that the default behavior of the omnibox is to search both history and bookmarks. But the answer set drop down seems limited to 5 entries, so who knows how Chrome is ordering that answer set. The stickynotes entry does not show up until sti is entered. With s and st entered, there are 5 other entries listed. 
Plus this article seems to indicate that Chrome behavior has changed recently.
https://www.ghacks.net/2019/05/14/fix-chrome-prioritizing-search-words-over-visited-sites-in-address-bar/

**Comment by brainfoolong** [comment]
This reason is why bomnibox exist. Straight forward history search, sorted by most used urls just by searching the text without any fancy algorithm and weird priorizing behaviours.

**Comment by pbajorek** [comment]
Thank you.
